//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDiyethane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDIYETLER
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public string DIYETBAGLANTI { get; set; }
        public string DIYETRESIM { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLYAZAR TBLYAZAR { get; set; }
    }
}
